import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["100","200","300","400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`md:mx-10 my-4 bg-black text-white ${poppins.className}mx-3 bg-[url("/BackgroundPattern.png")] bg-cover `}>
      <Header/>
      {children}
      <Footer/></body>
    </html>
  );
}
